{% set name = "libuldaq" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mccdaq/uldaq/archive/v{{ version }}.tar.gz
  sha256: 45a72e2ae41d4bdeb4ffe873e28fda471708d53a8511b3ebfc41166eb43e8381
  patches:
    - 0001-configure.ac-use-PKG_CHECK_MODULES.patch
    - 0002-makefile.am-remove-installation-of-udev-rules.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - libusb
    - pkg-config
  host:
    - libusb

test:
  commands:
    - test -f ${PREFIX}/lib/libuldaq${SHLIB_EXT}

about:
  home: https://github.com/mccdaq/uldaq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Contains a library to access and control supported Measurement Computing DAQ devices
  description: The **uldaq** package contains programming libraries and components for developing applications using C/C++ on Linux and macOS Operating Systems. An API (Application Prog    ramming Interface) for interacting with the library in Python is available as an additional installation. This package was created and
    is supported by MCC.

extra:
  recipe-maintainers:
    - jdowner
